# Generated by Django 6.0 on 2025-12-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gener', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text_description', models.TextField(max_length=600)),
                ('prologo', models.TextField(max_length=100)),
                ('imagen_portada', models.ImageField(blank=True, upload_to='')),
                ('date_of_post', models.DateField(auto_now=True)),
                ('genero', models.ManyToManyField(to='novels.genero')),
            ],
        ),
    ]
