# Generated by Django 6.0 on 2025-12-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
