# Generated by Django 6.0 on 2026-01-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_alter_description_imagen_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firts_names', models.CharField(max_length=100, verbose_name='Nombres del Autor')),
                ('lasts_names', models.CharField(max_length=100, verbose_name='Apellidos del Autor')),
                ('age', models.PositiveBigIntegerField(verbose_name='Edad')),
            ],
        ),
        migrations.CreateModel(
            name='Novela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personajes', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='author',
            field=models.ManyToManyField(to='novels.author'),
        ),
    ]
